#!/usr/bin/env zsh

EFFECTIVE_STOW_DIR="$(pwd)/$(hostname)"

if [ ! -d "$EFFECTIVE_STOW_DIR" ];
then
	echo "no config for the $(hostname). aborting"
	exit 0
fi

if [ ! "$(ls -A $EFFECTIVE_STOW_DIR)" ];
then
	echo "no configs for the $(hostname) exist. aborting."
	exit 0
fi

echo "configuring $(hostname)..."

stow \
	--dir=$EFFECTIVE_STOW_DIR \
	--target=/ \
	--verbose=0 \
	.	

